### ISSUE TITLE
Plugin info api

### ISSUE THREAD

**Issue by marvin1099** [saadbruno/openrct2_plugin_repository#37]
So I have made a package manager for openrct plugins
[https://github.com/marvin1099/OpenRCT-Plugin-PM](https://github.com/marvin1099/OpenRCT-Plugin-PM) 
It works by webscaping the webside
[openrct2plugins.org](openrct2plugins.org) 
and at first I didn't think an API would be that important, but it would make the package manager more elegant and the plugin website more versatile.
I already talked about it in Discord and Saadbruno asked me if he should implement it.
At this point it may or may not be worked on, I created this topic mainly so that the status of the implementation can be easily verified.
If there is no interest in this feature, you can of course say so or close the issue.
Btw. "lastupdate" wold be a unix timestamp in this example.
Here is my idea of how the api could look like:
Reqest --------

https://api.openrct2plugins.org/?getjson=true?query=grass?maxresults=10

 Or i could be reqested like this -------

https://openrct2plugins.org/?api=true?getjson=true?query=grass?maxresults=10
 
```
Result -----
{
    "resultsnr":"3"
    "results":[
        {
            "pluginname":"openrct2-auto-mow",
            "plugindataurl":"https://openrct2plugins.org/plugin/R_kgDOHLFjjQ/openrct2-auto-mow",
            "plugingeturl":"https://github.com/PhasecoreX/openrct2-auto-mow/releases/latest",
            "lastupdate":1694292469
        },
        {
            ...
        },
        {
            ...
        }
    ]
}
```

**Comment by marvin1099** [comment]
/

**Comment by tubbo** [comment]
I also tried doing something like this (http://github.com/tubbo/rctpm), but couldn't use openrct2plugins.org because scraping the site was too unpredictable, especially at the time. Unfortunately, it doesn't seem like distributing plugins over NPM really took off, so I would be all about something like this!

**Comment by marvin1099** [comment]
True its unpredictable, I tryed to do it in this project [OpenRCT-Plugin-PM](https://github.com/marvin1099/OpenRCT-Plugin-PM) but some plugins just won't work, but the reason is related to the way that users upload the plugins.
Some have it in the releases and some have it in the repo.

**Comment by saadbruno** [comment]
Thanks for the suggestions, guys. I've added support to show any page result as json.
Just add `?json` to any URL in the website, and it should show the results.

Examples:  
List: https://openrct2plugins.org/list/?sort=new&p=2&results=50&json  
User: https://openrct2plugins.org/user/MDQ6VXNlcjEyODMyOTA2/?json  
Search: https://openrct2plugins.org/list/?search=scenario&json
Plugin: https://openrct2plugins.org/plugin/R_kgDOMS2c-g/?json

Lemme know if that works for you guys!
